package com.gzq.uiframework.renderer.node

object PropKeys {
    const val TEXT: String = "text"
    const val VALUE: String = "value"
    const val ON_CLICK: String = "on_click"
    const val ON_VALUE_CHANGE: String = "on_value_change"
    const val HINT: String = "hint"
    const val SINGLE_LINE: String = "single_line"
    const val TEXT_FIELD_TYPE: String = "text_field_type"
    const val HINT_TEXT_COLOR: String = "hint_text_color"
    const val VIEW_FACTORY: String = "view_factory"
    const val VIEW_UPDATE: String = "view_update"
    const val BOX_ALIGNMENT: String = "box_alignment"
    const val LAZY_ITEMS: String = "lazy_items"
    const val TAB_PAGES: String = "tab_pages"
    const val SELECTED_TAB_INDEX: String = "selected_tab_index"
    const val ON_TAB_SELECTED: String = "on_tab_selected"
    const val LINEAR_SPACING: String = "linear_spacing"
    const val ROW_MAIN_AXIS_ARRANGEMENT: String = "row_main_axis_arrangement"
    const val COLUMN_MAIN_AXIS_ARRANGEMENT: String = "column_main_axis_arrangement"
    const val ROW_VERTICAL_ALIGNMENT: String = "row_vertical_alignment"
    const val COLUMN_HORIZONTAL_ALIGNMENT: String = "column_horizontal_alignment"
    const val DIVIDER_COLOR: String = "divider_color"
    const val DIVIDER_THICKNESS: String = "divider_thickness"
}
