package com.gzq.uiframework.renderer.node

object TypedPropKeys {
    val Text = PropKey<CharSequence>(PropKeys.TEXT)
    val TextColor = PropKey<Int>(PropKeys.TEXT_COLOR)
    val TextSizeSp = PropKey<Int>(PropKeys.TEXT_SIZE_SP)
    val TextMaxLines = PropKey<Int>(PropKeys.TEXT_MAX_LINES)
    val TextOverflow = PropKey<TextOverflow>(PropKeys.TEXT_OVERFLOW)
    val TextAlign = PropKey<TextAlign>(PropKeys.TEXT_ALIGN)

    val Enabled = PropKey<Boolean>(PropKeys.ENABLED)
    val OnClick = PropKey<(() -> Unit)?>(PropKeys.ON_CLICK)

    val ButtonLeadingIcon = PropKey<ImageSource.Resource>(PropKeys.BUTTON_LEADING_ICON)
    val ButtonTrailingIcon = PropKey<ImageSource.Resource>(PropKeys.BUTTON_TRAILING_ICON)
    val ButtonIconSize = PropKey<Int>(PropKeys.BUTTON_ICON_SIZE)
    val ButtonIconSpacing = PropKey<Int>(PropKeys.BUTTON_ICON_SPACING)

    val ImageSource = PropKey<ImageSource>(PropKeys.IMAGE_SOURCE)
    val ImageContentScale = PropKey<ImageContentScale>(PropKeys.IMAGE_CONTENT_SCALE)
    val ImageContentDescription = PropKey<String>(PropKeys.IMAGE_CONTENT_DESCRIPTION)
    val ImageTint = PropKey<Int>(PropKeys.IMAGE_TINT)
    val ImageRemoteLoader = PropKey<RemoteImageLoader>(PropKeys.IMAGE_REMOTE_LOADER)
    val ImagePlaceholder = PropKey<ImageSource.Resource>(PropKeys.IMAGE_PLACEHOLDER)
    val ImageError = PropKey<ImageSource.Resource>(PropKeys.IMAGE_ERROR)
    val ImageFallback = PropKey<ImageSource.Resource>(PropKeys.IMAGE_FALLBACK)

    val Value = PropKey<String>(PropKeys.VALUE)
    val OnValueChange = PropKey<(String) -> Unit>(PropKeys.ON_VALUE_CHANGE)
    val Hint = PropKey<String>(PropKeys.HINT)
    val Label = PropKey<String>(PropKeys.LABEL)
    val Placeholder = PropKey<String>(PropKeys.PLACEHOLDER)
    val SupportingText = PropKey<String>(PropKeys.SUPPORTING_TEXT)
    val SingleLine = PropKey<Boolean>(PropKeys.SINGLE_LINE)
    val TextFieldType = PropKey<TextFieldType>(PropKeys.TEXT_FIELD_TYPE)
    val ReadOnly = PropKey<Boolean>(PropKeys.READ_ONLY)
    val MaxLines = PropKey<Int>(PropKeys.MAX_LINES)
    val MinLines = PropKey<Int>(PropKeys.MIN_LINES)
    val ImeAction = PropKey<TextFieldImeAction>(PropKeys.IME_ACTION)
    val HintTextColor = PropKey<Int>(PropKeys.HINT_TEXT_COLOR)
    val LabelTextColor = PropKey<Int>(PropKeys.LABEL_TEXT_COLOR)
    val SupportingTextColor = PropKey<Int>(PropKeys.SUPPORTING_TEXT_COLOR)
    val LabelTextSizeSp = PropKey<Int>(PropKeys.LABEL_TEXT_SIZE_SP)
    val SupportingTextSizeSp = PropKey<Int>(PropKeys.SUPPORTING_TEXT_SIZE_SP)

    val StyleAlpha = PropKey<Float>(PropKeys.STYLE_ALPHA)
    val StyleBackgroundColor = PropKey<Int>(PropKeys.STYLE_BACKGROUND_COLOR)
    val StyleBorderWidth = PropKey<Int>(PropKeys.STYLE_BORDER_WIDTH)
    val StyleBorderColor = PropKey<Int>(PropKeys.STYLE_BORDER_COLOR)
    val StyleCornerRadius = PropKey<Int>(PropKeys.STYLE_CORNER_RADIUS)
    val StyleRippleColor = PropKey<Int>(PropKeys.STYLE_RIPPLE_COLOR)
    val StylePaddingLeft = PropKey<Int>(PropKeys.STYLE_PADDING_LEFT)
    val StylePaddingTop = PropKey<Int>(PropKeys.STYLE_PADDING_TOP)
    val StylePaddingRight = PropKey<Int>(PropKeys.STYLE_PADDING_RIGHT)
    val StylePaddingBottom = PropKey<Int>(PropKeys.STYLE_PADDING_BOTTOM)
    val StyleMinHeight = PropKey<Int>(PropKeys.STYLE_MIN_HEIGHT)

    val ViewFactory = PropKey<(android.content.Context) -> android.view.View>(PropKeys.VIEW_FACTORY)
    val ViewUpdate = PropKey<(android.view.View) -> Unit>(PropKeys.VIEW_UPDATE)
}
