package com.gzq.uiframework.renderer.node

object TypedPropKeys {
    val Text = PropKey<CharSequence>(PropKeys.TEXT)
    val TextColor = PropKey<Int>(PropKeys.TEXT_COLOR)
    val TextSizeSp = PropKey<Int>(PropKeys.TEXT_SIZE_SP)
    val TextMaxLines = PropKey<Int>(PropKeys.TEXT_MAX_LINES)
    val TextOverflow = PropKey<TextOverflow>(PropKeys.TEXT_OVERFLOW)
    val TextAlign = PropKey<TextAlign>(PropKeys.TEXT_ALIGN)

    val Enabled = PropKey<Boolean>(PropKeys.ENABLED)
    val OnClick = PropKey<(() -> Unit)?>(PropKeys.ON_CLICK)
    val Checked = PropKey<Boolean>(PropKeys.CHECKED)
    val ControlColor = PropKey<Int>(PropKeys.CONTROL_COLOR)
    val OnCheckedChange = PropKey<(Boolean) -> Unit>(PropKeys.ON_CHECKED_CHANGE)
    val OnSliderValueChange = PropKey<(Int) -> Unit>(PropKeys.ON_SLIDER_VALUE_CHANGE)

    val ButtonLeadingIcon = PropKey<ImageSource.Resource>(PropKeys.BUTTON_LEADING_ICON)
    val ButtonTrailingIcon = PropKey<ImageSource.Resource>(PropKeys.BUTTON_TRAILING_ICON)
    val ButtonIconSize = PropKey<Int>(PropKeys.BUTTON_ICON_SIZE)
    val ButtonIconSpacing = PropKey<Int>(PropKeys.BUTTON_ICON_SPACING)

    val ImageSource = PropKey<ImageSource>(PropKeys.IMAGE_SOURCE)
    val ImageContentScale = PropKey<ImageContentScale>(PropKeys.IMAGE_CONTENT_SCALE)
    val ImageContentDescription = PropKey<String>(PropKeys.IMAGE_CONTENT_DESCRIPTION)
    val ImageTint = PropKey<Int>(PropKeys.IMAGE_TINT)
    val ImageRemoteLoader = PropKey<RemoteImageLoader>(PropKeys.IMAGE_REMOTE_LOADER)
    val ImagePlaceholder = PropKey<ImageSource.Resource>(PropKeys.IMAGE_PLACEHOLDER)
    val ImageError = PropKey<ImageSource.Resource>(PropKeys.IMAGE_ERROR)
    val ImageFallback = PropKey<ImageSource.Resource>(PropKeys.IMAGE_FALLBACK)

    val Value = PropKey<String>(PropKeys.VALUE)
    val OnValueChange = PropKey<(String) -> Unit>(PropKeys.ON_VALUE_CHANGE)
    val Hint = PropKey<String>(PropKeys.HINT)
    val Label = PropKey<String>(PropKeys.LABEL)
    val Placeholder = PropKey<String>(PropKeys.PLACEHOLDER)
    val SupportingText = PropKey<String>(PropKeys.SUPPORTING_TEXT)
    val SingleLine = PropKey<Boolean>(PropKeys.SINGLE_LINE)
    val TextFieldType = PropKey<TextFieldType>(PropKeys.TEXT_FIELD_TYPE)
    val ReadOnly = PropKey<Boolean>(PropKeys.READ_ONLY)
    val MaxLines = PropKey<Int>(PropKeys.MAX_LINES)
    val MinLines = PropKey<Int>(PropKeys.MIN_LINES)
    val ImeAction = PropKey<TextFieldImeAction>(PropKeys.IME_ACTION)
    val HintTextColor = PropKey<Int>(PropKeys.HINT_TEXT_COLOR)
    val LabelTextColor = PropKey<Int>(PropKeys.LABEL_TEXT_COLOR)
    val SupportingTextColor = PropKey<Int>(PropKeys.SUPPORTING_TEXT_COLOR)
    val LabelTextSizeSp = PropKey<Int>(PropKeys.LABEL_TEXT_SIZE_SP)
    val SupportingTextSizeSp = PropKey<Int>(PropKeys.SUPPORTING_TEXT_SIZE_SP)

    val SliderValue = PropKey<Int>(PropKeys.SLIDER_VALUE)
    val MinValue = PropKey<Int>(PropKeys.MIN_VALUE)
    val MaxValue = PropKey<Int>(PropKeys.MAX_VALUE)

    val ProgressFraction = PropKey<Float>(PropKeys.PROGRESS_FRACTION)
    val ProgressIndicatorColor = PropKey<Int>(PropKeys.PROGRESS_INDICATOR_COLOR)
    val ProgressTrackColor = PropKey<Int>(PropKeys.PROGRESS_TRACK_COLOR)
    val ProgressTrackThickness = PropKey<Int>(PropKeys.PROGRESS_TRACK_THICKNESS)
    val ProgressIndicatorSize = PropKey<Int>(PropKeys.PROGRESS_INDICATOR_SIZE)

    val BoxAlignment = PropKey<com.gzq.uiframework.renderer.layout.BoxAlignment>(PropKeys.BOX_ALIGNMENT)
    val LinearSpacing = PropKey<Int>(PropKeys.LINEAR_SPACING)
    val RowMainAxisArrangement = PropKey<com.gzq.uiframework.renderer.layout.MainAxisArrangement>(PropKeys.ROW_MAIN_AXIS_ARRANGEMENT)
    val ColumnMainAxisArrangement = PropKey<com.gzq.uiframework.renderer.layout.MainAxisArrangement>(PropKeys.COLUMN_MAIN_AXIS_ARRANGEMENT)
    val RowVerticalAlignment = PropKey<com.gzq.uiframework.renderer.layout.VerticalAlignment>(PropKeys.ROW_VERTICAL_ALIGNMENT)
    val ColumnHorizontalAlignment = PropKey<com.gzq.uiframework.renderer.layout.HorizontalAlignment>(PropKeys.COLUMN_HORIZONTAL_ALIGNMENT)

    val LazyItems = PropKey<List<LazyListItem>>(PropKeys.LAZY_ITEMS)
    val LazyContentPadding = PropKey<Int>(PropKeys.LAZY_CONTENT_PADDING)
    val LazySpacing = PropKey<Int>(PropKeys.LAZY_SPACING)

    val SegmentItems = PropKey<List<SegmentedControlItem>>(PropKeys.SEGMENT_ITEMS)
    val SegmentSelectedIndex = PropKey<Int>(PropKeys.SEGMENT_SELECTED_INDEX)
    val OnSegmentSelected = PropKey<(Int) -> Unit>(PropKeys.ON_SEGMENT_SELECTED)
    val SegmentBackgroundColor = PropKey<Int>(PropKeys.SEGMENT_BACKGROUND_COLOR)
    val SegmentIndicatorColor = PropKey<Int>(PropKeys.SEGMENT_INDICATOR_COLOR)
    val SegmentCornerRadius = PropKey<Int>(PropKeys.SEGMENT_CORNER_RADIUS)
    val SegmentTextColor = PropKey<Int>(PropKeys.SEGMENT_TEXT_COLOR)
    val SegmentSelectedTextColor = PropKey<Int>(PropKeys.SEGMENT_SELECTED_TEXT_COLOR)
    val SegmentRippleColor = PropKey<Int>(PropKeys.SEGMENT_RIPPLE_COLOR)
    val SegmentTextSizeSp = PropKey<Int>(PropKeys.SEGMENT_TEXT_SIZE_SP)
    val SegmentContentPaddingHorizontal = PropKey<Int>(PropKeys.SEGMENT_CONTENT_PADDING_HORIZONTAL)
    val SegmentContentPaddingVertical = PropKey<Int>(PropKeys.SEGMENT_CONTENT_PADDING_VERTICAL)

    val DividerColor = PropKey<Int>(PropKeys.DIVIDER_COLOR)
    val DividerThickness = PropKey<Int>(PropKeys.DIVIDER_THICKNESS)

    val StyleAlpha = PropKey<Float>(PropKeys.STYLE_ALPHA)
    val StyleBackgroundColor = PropKey<Int>(PropKeys.STYLE_BACKGROUND_COLOR)
    val StyleBorderWidth = PropKey<Int>(PropKeys.STYLE_BORDER_WIDTH)
    val StyleBorderColor = PropKey<Int>(PropKeys.STYLE_BORDER_COLOR)
    val StyleCornerRadius = PropKey<Int>(PropKeys.STYLE_CORNER_RADIUS)
    val StyleRippleColor = PropKey<Int>(PropKeys.STYLE_RIPPLE_COLOR)
    val StylePaddingLeft = PropKey<Int>(PropKeys.STYLE_PADDING_LEFT)
    val StylePaddingTop = PropKey<Int>(PropKeys.STYLE_PADDING_TOP)
    val StylePaddingRight = PropKey<Int>(PropKeys.STYLE_PADDING_RIGHT)
    val StylePaddingBottom = PropKey<Int>(PropKeys.STYLE_PADDING_BOTTOM)
    val StyleMinHeight = PropKey<Int>(PropKeys.STYLE_MIN_HEIGHT)

    val ViewFactory = PropKey<(android.content.Context) -> android.view.View>(PropKeys.VIEW_FACTORY)
    val ViewUpdate = PropKey<(android.view.View) -> Unit>(PropKeys.VIEW_UPDATE)
    val AnchorId = PropKey<String>(PropKeys.ANCHOR_ID)
}
